FROM python:3.11-slim

WORKDIR /usr/src/flask_movie

RUN apt-get update  \
    && apt-get install -y --no-install-recommends netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1

RUN pip install --no-cache-dir poetry

COPY ./pyproject.toml ./poetry.lock* ./
RUN poetry install --no-root --no-directory

COPY . .
