upstream api {
    server flask_movie-api-1:8001;
}


server {
    listen 80;
    server_name localhost;
    # server_name 3.88.114.232 ec2-3-88-114-232.compute-1.amazonaws.com;

    location / {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /flask_movie/static/;
        add_header Cache-Control "public, no-transform";
    }
    location /media/ {
        alias /flask_movie/media/;
        add_header Cache-Control "public, no-transform";
    }

}